### PR TITLE
Add option in vehicle stats to choose what mileage metric to show

### PR DESCRIPTION
**Pull request by AlfHou**
Adds a dropdown menu above the vehicle stats graph to select the prefered fuel consumption metric.
image

### CODE REVIEW

**Comment by marc115uk** [comment]
Have just updated my container from akhilrex/hammond version to alfhou/hammond, how do I see the option to change to mpg as not showing on my version thanks :)

**Comment by AlfHou** [comment]
Hi! I thought these were merged on the fork, however they weren't. The changes should be included in release [v0.0.2](https://github.com/AlfHou/hammond/releases/tag/v0.0.2).
It should be rolled out to docker [shortly](https://github.com/AlfHou/hammond/actions/runs/4034012166)

**Comment by marc115uk** [comment]
Many thanks

**Comment by marc115uk** [comment]
Could we add imperial gallons as well as US, 4.54609 litres per gallon 
thanks

**Pull request merged**
